### ISSUE TITLE
NodeRED Login not working with docker based deployment

### ISSUE THREAD

**Issue by akashtalole** [flowforge/docker-compose#1]
### Current Behavior

NodeRED Login not working with docker based deployment.
It is giving below error when click on Sign in
[Error](https://prnt.sc/26hbvgh)

### Expected Behavior

It should login into Nodered

### Steps To Reproduce

- ./build-containers.sh
- docker-compose up
- Setup Flow forge
- Login to flowforge
- Create team
- Create Project
- Access project url
- Try to login

### Environment

- FlowForge version: 0.0.1
- Node.js version: 16
- npm version:
- Platform/OS: Docker on Ubuntu 20.04
- Browser: Chrome

**Comment by akashtalole** [comment]
Audit log for project access
[Audit log screenshot](https://prnt.sc/26hbzjs)

**Comment by hardillb** [comment]
What values did you setup up in the `etc/flowforge.yml` before running`docker-compose up` and what DNS entries did you create?

**Comment by akashtalole** [comment]
I am using default values in flowforge.yml.
I just added /etc/hosts entries in my local system as below
`127.0.0.1       example.com forge.example.com helpful-brambling-5444.example.com clever-evening-grosbeak-5099.example.com`

**Comment by hardillb** [comment]
That won't work, first the you can't put a domain in `/etc/hosts` it can only be full hosts so remove `example.com`

Second you need to use the external IP address of the host machine, because 127.0.0.1 will always point to the machine (or container) doing the lookup, hence why the container are failing to connect to themselves on port 80 since the Ngnix is only listening on the host machine.

**Comment by akashtalole** [comment]
Thanks @hardillb for quick reply.
It is working now with my local system IP.
`192.168.204.63  forge.example.com helpful-brambling-5444.example.com clever-evening-grosbeak-5099.example.com`

**Comment by knolleary** [comment]
We should add a brief the words about dns config to the readme - with an example.
