### ISSUE TITLE
Error build container flowforge-docker

### ISSUE THREAD

**Issue by 9223000** [flowforge/docker-compose#19]
### Current Behavior

#6 [3/8] RUN apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev python2
#6 sha256:b003b42649edf125f677da76f3f351736b382f178594fd67e6abf39703182c17
#6 0.293 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#6 0.895 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#6 1.349 ERROR: unable to select packages:
#6 1.384   build-base-20220619.134549:
#6 1.384     masked in: cache
#6 1.384     satisfies: world[build-base=20220619.134549]
#6 1.384   python2 (no such package):
#6 1.384     required by: build-base-20220619.134549[python2]
#6 ERROR: executor failed running [/bin/sh -c apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev python2]: exit code: 2
------
 > [3/8] RUN apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev python2:
------
executor failed running [/bin/sh -c apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev python2]: exit code: 2
#1 [internal] load build definition from Dockerfile
#1 sha256:2e5910675e7831efd1a9542e77e271aef7cd3ffe17ec2bf81c8f8d9c6d1727d2
#1 transferring dockerfile: 32B done
#1 DONE 0.0s

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by 9223000** [comment]
# RUN apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev python2
RUN apk add --no-cache --virtual build-base g++ make py3-pip sqlite-dev

**Comment by hardillb** [comment]
This is because the NodeJS container just moved to Alpine 3.16 which totally dropped Python 2.

I spotted this on Friday while playing with the k8s containers and didn't get around to flagging it on the docker version as well. Will check in fixes for both Monday
