### ISSUE TITLE
Project nodered instance state unhealthy

### ISSUE THREAD

**Issue by akashtalole** [flowforge/docker-compose#23]
### Current Behavior

Not able to access nodered instance for project

### Expected Behavior

Nodered editor should be accessible

### Steps To Reproduce

docker-compose up
create project and wait for conatiner up and running

### Environment

- FlowForge version: 0.7.1
- Node.js version: 16
- npm version: 
- Platform/OS: Ubuntu 20.04
- Browser: Chrome

I can see below logs for created nodred instance

```
Launcher Started
Loading project settings
(node:1) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo EAI_AGAIN forge
    at ClientRequest.<anonymous> (/usr/src/flowforge-nr-launcher/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/usr/src/flowforge-nr-launcher/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by hardillb** [comment]
Can we have a little bit more details here please.

I assume you followed the instructions from here: https://github.com/flowforge/flowforge/blob/main/docs/install/docker/README.md

Can you outline any configuration changes you have made (edits to the `etc/flowforge.yml` file)

**Comment by hardillb** [comment]
Also was this a fresh deployment or an upgrade?

**Comment by akashtalole** [comment]
On my system i found 2 docker networks for flowforge
1. docker-compose_flowforge
2. flowforge-071_flowforge

I launched new docker compose(flowforge-071_flowforge) but nodered project was created under docker-compose_flowforge network. due to which connection issue observed.

I found below code which is responsible for launching nodered instances for docker. it is searching network using label and taking 0th network by deafult. If there are multiple flowforge networks then this issue occurs.
https://github.com/flowforge/flowforge-driver-docker/blob/8dc21bf91d4701ce928d0153780df375c0fea1b9/docker.js#L5
`    const networks = await this._docker.listNetworks({ filters: { label: ['com.docker.compose.network=flowforge'] } })
    const stack = project.ProjectStack.properties
    const contOptions = {
        Image: stack.container,
        name: project.id, // options.name,
        Env: [],
        Labels: {},
        AttachStdin: false,
        AttachStdout: false,
        AttachStderr: false,
        HostConfig: {
            NetworkMode: networks[0].Name
        }
    }`

**Comment by hardillb** [comment]
@akashtalole thanks for the update, yes it does make some assumptions about the network which should hold if all the defaults hold.

Please supply some information about how you had created the extra network and how you had brought up the system, just so we can improve the documentation.

We can also look at how to allow a little more customisation.

**Comment by akashtalole** [comment]
Due to my earlier flowforge setup, docker compose network was present for older version. Today I have created another docker compose up which basically created another network which causes this issue.

**Comment by nileio** [comment]
hi team - I came across this issue after trying to figure out the reason of the service failing to start .. If we have to rely on a particular network name, is it possible that we allow the creation of docker networks externally and only reference it in compose ? 
as in
``` 
networks:
  flowforge: 
    external: true
``` 
so not rely on docker compose to create it ? we need to manage the networks external to docker compose and so we want flowfuse to simply join that network only.. also by letting compose create the networks it goes all weird with adding prefixes _ (using project name, etc.) and can get messy trying to clear all the networks especially on non-prod .. any thoughts ? Thank you
