### ISSUE TITLE
flowforge broker error

### ISSUE THREAD

**Issue by akashtalole** [flowforge/docker-compose#29]
### Current Behavior

Getting below error 
`flowforge-broker_1  | 1661053671: Bad socket read/write on client forge_platform: Unknown error.
forge_1             | [2022-08-21T03:47:56.344Z] INFO: Reconnecting to comms broker
flowforge-broker_1  | 1661053676: New connection from 172.23.0.5:36780 on port 1883.
flowforge-broker_1  | time="2022-08-21T03:47:56Z" level=error msg="http request error: Post \"http://forge:80/api/comms/auth/client\": dial tcp 172.23.0.5:80: connect: connection refused"
flowforge-broker_1  | time="2022-08-21T03:47:56Z" level=error msg="Post \"http://forge:80/api/comms/auth/client\": dial tcp 172.23.0.5:80: connect: connection refused"
`

### Steps To Reproduce

docker-compose up

### Environment

- FlowForge version: 0.8.0
- Node.js version: 16.13.2
- npm version:
- Platform/OS: Ubuntu 20.04
- Browser: Chrome

**Comment by hardillb** [comment]
edit the `broker/mosquitt.conf` file to change the `auth_opt_http_port` number to `3000`

```
auth_opt_http_host forge
auth_opt_http_port 3000
auth_opt_http_getuser_uri /api/comms/auth/client
auth_opt_http_aclcheck_uri /api/comms/auth/acl
```

**Comment by akashtalole** [comment]
Thanks @hardillb . Its working fine with updated port
