### ISSUE TITLE
New version of Postgres causing SQL errors

### ISSUE THREAD

**Issue by robmarcer** [flowforge/docker-compose#43]
### Current Behavior

When running the docker compose up command the database cannot be accessed by the main FlowForge container

### Expected Behavior

The database should be accessible.

### Steps To Reproduce

Run the docker compose up command.

This issue can be fixed by editing the docker-compose.yml to use image: postgres:14

### Environment

- FlowForge version: Current
- Node.js version: Current
- npm version: Current
- Platform/OS: GCP
- Browser: Chome current

**Comment by hardillb** [comment]
@robmarcer Since this worked for you when I pinned it to v14 I'm moving this to done
