### ISSUE TITLE
Unable to access nodered created using project

### ISSUE THREAD

**Issue by akashtalole** [flowforge/docker-compose#60]
### Current Behavior

While acessing nodered getting below error
`Error: getaddrinfo EAI_AGAIN forge.example.com`
![nr-err](https://user-images.githubusercontent.com/10166338/205219799-d35f3f73-7b96-4113-8b03-6574fa5d6e90.png)

### Expected Behavior

nodered should be accessible

### Environment

- FlowForge version: v1.1.0
- Node.js version: v16.17.0
- npm version:
- Platform/OS: Windows 11 Docker
- Browser: Chrome

**Comment by hardillb** [comment]
FlowForge on Docker uses hostname based routing. To make this work you need to provide a DNS domain in the `etc/flowforge.yml` file and configure your DNS to resolve that domain to the machine hosting Docker.

This is mentioned in the documentation [here](https://flowforge.com/docs/install/docker/#dns) 

> ## DNS
> 
> The orchestration uses an instance of Nginx to route requests to each Node-RED Project. To do this it needs each instance to have a unique hostname, to generate this the project name is prepended to a supplied domain.
> 
> To make this work you will need to configure a DNS server to map a wildcard domain entry to the IP address of the host running Docker. e.g *.example.com.
> 
> The FlowForge Application will be hosted on http://forge.example.com
> 
> Note When testing locally you can add entries for each project to your /etc/hosts file but you must use the external IP address of the host machine, not the loopback address (127.0.0.1).
> 

And in the Configuring FlowForge section [here](https://flowforge.com/docs/install/docker/#configuring-flowforge)

> 
> Configuring FlowForge
> 
> Configuration details are stored in the `etc/flowforge.yml` file which is mapped into the `flowforge/forge-docker` container. You will need to edit this file to update the `domain` and `base_url` entries to match the DNS settings. Please note that once set, the `domain` and `base_url` values should not be changed as these values are used as part of the configuration stored in the database of each project. The ability to migrate domains is on the feature backlog.
> 
> You also need to update the `VIRTUAL_HOST` entry in the `docker-compose.yml` file to use the same domain as in the `etc/flowforge.yml` file.
> 
> For more details on the options available, see the [configuration guide](https://flowforge.com/docs/install/configuration).

Both of these sections are also in the README.md for the project.

Documentation about how to setup DNS for local testing is coming soon (but will does not cover Windows as I can't find a suitable DNS server to run on Windows).

**Comment by akashtalole** [comment]
I have host file entries in windows. It was working before. Today i updated Docker desktop. Will check it once after rebooting system.

**Comment by akashtalole** [comment]
hostname resoultion is working from my system cmd but it is not resolving from conatiner.

**Comment by hardillb** [comment]
Yes, this is expected, because the containers can't see your hosts file

**Comment by akashtalole** [comment]
I have stopped nodered container and copied docker run command. Added `--add-host forge.example.com:<IP>` in that command and created new container manually. Now its acessible
