### ISSUE TITLE
Nodered Project not starting (shows as installing) 

### ISSUE THREAD

**Issue by blueoceans2002** [flowforge/docker-compose#68]
Hi,
I have setup the app on aws EC2 and domain . Interestingly when I create a project it shows as starting or installing. I even bumped the server to large instance but no luck

I have attached the screenshot, any help in how to get this working will be highly appreciated

![805CBF07-ADCE-4002-B4E4-3E0566BF954C](https://user-images.githubusercontent.com/119927769/208286916-3222732f-bd30-42be-9094-8acdebd6485d.png)

![6B79B706-5B70-44B7-AF55-8BA680739B9B](https://user-images.githubusercontent.com/119927769/208286913-83049bd3-fd1a-4dc9-ad5f-54e0085b40a6.jpeg)

thanks 
Satish

**Comment by hardillb** [comment]
How lond did you leave the project when in "installing" state and what was shown on the logs tab?

**Comment by blueoceans2002** [comment]
Hi @hardillb 
This is what I see on each Projects log tab. The projects were created 5 hrs ago
![image](https://user-images.githubusercontent.com/119927769/208297726-6b8c15a2-d6c6-4f63-bbb2-ce0736f46a05.png)

![image](https://user-images.githubusercontent.com/119927769/208297765-3e22e01e-5673-44b4-8c12-ca960cf6f1dd.png)

**Comment by hardillb** [comment]
Please show you stack settings

**Comment by blueoceans2002** [comment]
@hardillb please find attached
![3B5517F3-A319-4692-B771-B915047A4AA3](https://user-images.githubusercontent.com/119927769/208299438-07eb987b-8336-41b9-898d-9e17ff1d5688.jpeg)

**Comment by awan1995** [comment]
@hardillb 
<img width="1723" alt="Screenshot 2022-12-18 at 14 06 47" src="https://user-images.githubusercontent.com/51690798/208302908-35890db1-7514-4359-9a93-57e09496e965.png">
our app is being stuck at installing in  i have check the logs in depth in there i got this error when i start or restart the project

**Comment by hardillb** [comment]
@awan1995 is this the same instance as @blueoceans2002 is talking about?

**Comment by awan1995** [comment]
@blueoceans2002 Yes we both are working together

**Comment by hardillb** [comment]
I need details of your DNS setup and any entries you have put in the host machines `/etc/hosts` file

Nothing should be mapped to the 127.0.0.1 address

**Comment by hardillb** [comment]
I also still need to know what versions of  FlowForge you are running

**Comment by awan1995** [comment]
@hardillb okay sure let me send you

**Comment by awan1995** [comment]
<img width="717" alt="Screenshot 2022-12-18 at 14 16 40" src="https://user-images.githubusercontent.com/51690798/208303318-371439f7-0b71-45d1-b5e9-49720543ccdb.png">

**Comment by awan1995** [comment]
@hardillb  i have attached screenshot

**Comment by hardillb** [comment]
And the rest of the DNS information for `stellardock.com`. Have  you set up the wildcard domain mapping as required in the documentation?

**Comment by awan1995** [comment]
@hardillb yes i have added A Name Record for app subdomain and also generated a wildcard *.domain.com and added it to certs with default.crt and default.key as well

**Comment by hardillb** [comment]
Are you sure?

`app.stellardock.com` resolves to `3.26.34.182`

But

`long-citril-finch-9469.stellardock.com` does not resolve to anything, it should resolve to the same IP address as the the front end.

**Comment by awan1995** [comment]
@hardillb yes for the one i have added it in the DNS https://amused-lanceolated-warbler-9081.stellardock.com/

**Comment by hardillb** [comment]
You should not be manually adding entries to the DNS.

If you've set the wild card up properly it should match anything before the `stellardock.com` e.g. `foo.stellardock.com`

**Comment by awan1995** [comment]
@hardillb Okay sure i can add that wildcard

**Comment by awan1995** [comment]
@hardillb but i think atleast it should be working on https://amused-lanceolated-warbler-9081.stellardock.com/ em i right?

**Comment by hardillb** [comment]
Also Please answer the versions question I've asked multiple times now

**Comment by awan1995** [comment]
@hardillb oh sorry for that  i didn't see above version comment it v1.1.2 screenshot is also attached. Thanks
<img width="1172" alt="Screenshot 2022-12-18 at 14 30 35" src="https://user-images.githubusercontent.com/51690798/208303977-b7bc6adf-f4e4-4b4c-ba8a-39bb5ba91cc7.png">

**Comment by hardillb** [comment]
OK, I've just tried a fresh clean 1.1.2 install here and I'm not having a problem.

Please supply all of the following:

-  (not as an image) your `etc/flowforge.yml` file 
-  `docker-compose.yml` file you are running from.
- Details of the host machine you are running on memory/cpu cound

Also did you use the `build-containers.sh` or pull the pre-built images from docker hub?

**Comment by awan1995** [comment]
@hardillb 
docker-compose.yml
https://drive.google.com/file/d/1TDdAYNMWE7c0B_1SXTC1r0vCncNgKdkC/view?usp=sharing

flowforge.yml
https://drive.google.com/file/d/1dXATRUy8mjzv6MAbano5ozMPikoDmNvb/view?usp=sharing

8GB RAM AWS t3.large  vCPUs 2 8gb HDD from 30% is free

i think some problem is with this api_url :// forge:3000 when i change the value of forge it's not working now it is being installed but one more error it is giving which below one 
<img width="1702" alt="Screenshot 2022-12-18 at 16 38 10" src="https://user-images.githubusercontent.com/51690798/208309327-ff350037-b511-4d7b-bb35-5b04cf3bf0ff.png">
<img width="1412" alt="Screenshot 2022-12-18 at 16 38 30" src="https://user-images.githubusercontent.com/51690798/208309330-4b453ed5-9c80-4b3e-a761-14a01792b6d0.png">

**Comment by hardillb** [comment]
Please include the files in the update, not link to external sites, it makes reading them much harder than it needs to be.

You should never have changed the `api_url` (no where in the documentation does it say to change that value). If you have changed it, change it back and restart the whole docker-compose deployment.

**Comment by awan1995** [comment]
[docker-compose.yml.txt](https://github.com/flowforge/docker-compose/files/10254266/docker-compose.yml.txt)
[flowforge.yml.txt](https://github.com/flowforge/docker-compose/files/10254267/flowforge.yml.txt)


@hardillb i have attached it as a .txt because github isnot allowing me to attach .yml file

**Comment by hardillb** [comment]
I meant to inline them in code blocks. but leave it for now.

If you are getting to the point where you are trying to log in then it appears the installing/starting problem has passed? 

Having the wrong `api_url` entry will stop the containers from starting because the launcher in the project container will not be able to find the forge app to download it's settings and the project will not be able to authenticate or store flows.

**Comment by awan1995** [comment]
@hardillb okay problem has been passed but we we need to use forge.stellardock.com like with forge on the start or we can use any subdomain as the base_url like app.stellardock.com

**Comment by awan1995** [comment]
@hardillb Thanks for the help i have created a clean project but still i'm getting access token failed error don't know what to change nothing this time in it only change example with stelllardock but access token failed is coming if you know any thing about please let me know thanks

**Comment by hardillb** [comment]
`base_url` points to the forge app, it does not need to be on the same domain as the projects which will be hosted on the value of `domain`. But both hostname in `base_url` and the wildcard DNS entry for `domain` must both resolve to the same IP address which is the box the docker instance is running on as they both need to be proxied by the same nginx instance.

e.g. `base_name` can be `https://forge.example.com` and `domain` could be `projects.example.com`  or `projects.com`. Just as long as they all resolve to the same address.

`api_url` should always be `http://forge:3000` on the docker-compose based systems.

If you have changed any of the `api_url`, `base_url` or `domain` you should do the following steps:

1. delete all the projects
2. stop the system (`docker-compose -p flowforge down`)
3. delete the `db` directory (probably need sudo to do this as the files will be owned by the postgres user)
4. restart the system (`docker-compose -p flowforge up -d`)

Before trying to do anything else.

If you still have authentication failures you need to look at both the project logs and the browser logs.

**Comment by hardillb** [comment]
One other thing I've just noticed (sorry it was in the opening screen shot and I missed it), you created a project with the same name as you used for the `base_name` e.g. "app".  If you are using the same `domain` for both the `base_name` and projects they will clash and break things.

**Comment by awan1995** [comment]
@hardillb yes that i just do for testing purpose same domain path have clash in them anyhow that project is now installing sucessfully but when i open the code editor for a project it says failed to get access token. i tried your all above mention ways even created a project from scratch but that access error is not going 
<img width="1699" alt="Screenshot 2022-12-18 at 22 59 55" src="https://user-images.githubusercontent.com/51690798/208324049-4b535dcc-2539-40d8-80b5-c253d5663a85.png">


<img width="1352" alt="Screenshot 2022-12-18 at 23 01 07" src="https://user-images.githubusercontent.com/51690798/208324038-e538b1ab-c7c2-4391-9dc0-b663421c9c5f.png">

**Comment by awan1995** [comment]
@hardillb app is unable to get the access the access token.

**Comment by hardillb** [comment]
Show the logs from the project at the same time

**Comment by awan1995** [comment]
@hardillb how i can see the projects logs?

**Comment by hardillb** [comment]
From the forge app

**Comment by awan1995** [comment]
port: 3000
host: 0.0.0.0
domain: stellardock.com
base_url: http://forge.stellardock.com
api_url: http://forge:3000

#################################################
# Database Configuration                        #
#################################################

db:
  logging: false
  ## The database type: sqlite|postgres
  type: postgres
  ### SQLite options

  ## The database filename. Relative to $FLOWFORGE_HOME/var/
  ## Set to ':memory:' for a database that is wiped on restart
  # storage: forge.db

  ### Postgres options

  host: postgres
  user: root
  password: secret

#################################################
# Project Driver Configuration                  #
#################################################

driver:
  ## The type of backend driver to use
  ##  Can be: localfs/docker/stub/k8s
  type: docker

  options:
    ## Options to be passed to the driver

    ### LocalFS options

    ## The first port number to assign to projects
    # start_port: 7880

    ## Path to find node executable if not on the default path
    # node_path: /usr/bin/node

    ### Docker options

    ## Docker socket path
    socket: /tmp/docker.sock
    # registry: hub.flowforge.com

    ### K8S options

    ## Kubectl conf file to contact the cluster
    # config_file: /opt/share/projects/flowforge/test/config
    # regsitry: hub.flowforge.com

#################################################
# Email Configuration                           #
#################################################

email:
  enabled: false
  debug: false
  smtp:
    host: localhost
    port: 587
    secure: false
    #auth:
    #    user: username
    #    pass: password

**Comment by awan1995** [comment]
@hardillb flowforge.yml is attached above

**Comment by awan1995** [comment]
@hardillb  Logs of the flowforge
<img width="1711" alt="Screenshot 2022-12-18 at 23 37 28" src="https://user-images.githubusercontent.com/51690798/208325483-25efc7cb-230d-4695-b689-5dbd6833dbc0.png">

**Comment by hardillb** [comment]
No, the logs tab for the project, in the web app

**Comment by awan1995** [comment]
@hardillb I think some problem with the credentials
<img width="1641" alt="Screenshot 2022-12-18 at 23 54 24" src="https://user-images.githubusercontent.com/51690798/208326163-74058e13-bb71-4dd5-bce4-40087f894a6e.png">

**Comment by awan1995** [comment]
@hardillb if encrypted credentials is the issue i have all the pem files in the certs folder

**Comment by awan1995** [comment]
<img width="829" alt="Screenshot 2022-12-18 at 23 57 10" src="https://user-images.githubusercontent.com/51690798/208326283-fd223022-f034-4d43-80fb-895b04c45495.png">

**Comment by hardillb** [comment]
Delete the project, then change

`base_url: http://forge.stellardock.com`

To

`base_url: https://forge.stellardock.com`

And restart

**Comment by awan1995** [comment]
@hardillb Okay

**Comment by awan1995** [comment]
@hardillb i have done that but now it is stuck in starting
<img width="1635" alt="Screenshot 2022-12-19 at 00 03 24" src="https://user-images.githubusercontent.com/51690798/208326532-44760546-0e26-4149-81b9-4e9706093d60.png">

<img width="1474" alt="Screenshot 2022-12-19 at 00 04 02" src="https://user-images.githubusercontent.com/51690798/208326553-a94210cc-bdf4-42f9-9a1d-5f288915431f.png">

**Comment by awan1995** [comment]
@hardillb it is running now but now new error is showing 
<img width="1700" alt="Screenshot 2022-12-19 at 00 06 26" src="https://user-images.githubusercontent.com/51690798/208326663-03acb228-225d-4d3b-86a4-b098b24e9381.png">

**Comment by hardillb** [comment]
You need to use the `fullchain.pem` for the `stelardock.com.crt` not the `cert.pem`

**Comment by awan1995** [comment]
@hardillb  Okei

**Comment by awan1995** [comment]
@hardillb  Okay

**Comment by awan1995** [comment]
@hardillb Thanks alot my app is working now  <3

**Comment by blueoceans2002** [comment]
Hi @hardillb  Big thanks for all the help. 

Interestingly I have a waning in Manage Palette
![image](https://user-images.githubusercontent.com/119927769/208328757-8da2008c-73d5-45d4-b9ca-1a765dfa2053.png)

@awan1995 fyi

**Comment by hardillb** [comment]
The warning about the Project Nodes is self explanatory, those are only available when FlowForge is used with a paid for Enterprise License.

As for the file nodes, you need to edit your template exclude `10-file.js` to stop the default core Node-RED file nodes being loaded so the FlowForge replacements will be loaded instead. (trying to use the core file nodes inside a docker container is not a good idea as the files will not be persisted anywhere.) (Similarly there is no need for the watch node since there will be no files, we also suggest disabling the TCP and UDP nodes since there is no way to accept incoming connection inside a container)

![Screenshot from 2022-12-19 09-12-07](https://user-images.githubusercontent.com/1800845/208389783-a0ff1487-2fd9-4334-9e48-b4f94504c11c.png)
