### ISSUE TITLE
Doc Req - what is the best practice to setup your Stack config 

### ISSUE THREAD

**Issue by blueoceans2002** [flowforge/docker-compose#69]
### Description

Flowforge is a great app, I have it setup on AWS ec2  with the help of @hardillb (Big thanks) and I am playing with it and loving it. 
I would like to know what is the best practice to setup the stack to allocate the resources, any minimum spec required?

Thanks
Satish

**Comment by hardillb** [comment]
You will have to experiment with those values to determine what is the best fit for the types of flows you expect people to run in projects.

But I would not go under 128mb of memory and 10% of a single CPU core (remember that NR is single threaded so will never us multiple cores)

**Comment by blueoceans2002** [comment]
@hardillb Big thanks for all the info on time. As you mentioned that NR is single threaded, if we run NR in different projects with different stacks configs, then we can make it run as multi threaded for parallel orchestration right?

**Comment by hardillb** [comment]
My point is that there is nothing to be gained by giving a stack more than 100% of a core.

Each Project is a separate instance of NR and each instance runs under the limits in the Stack, If you design a set of flows that distributes work across multiple projects/instances then you can make use of multiple cores.

**Comment by blueoceans2002** [comment]
Thanks @hardillb thats very helpful
