### ISSUE TITLE
The file-server version not updated

### ISSUE THREAD

**Issue by hardillb** [flowforge/docker-compose#80]
### Current Behavior

The current file-server/package.json still points to version 0.0.1

(The other option is to remove the build-containers.sh script as the containers are all now published to Docker hub, but if we do that we should still update the version number)

### Expected Behavior

running ./build-containers.sh should build the latest versions

### Steps To Reproduce

run ./build-containers.sh

### Environment

- FlowForge version: 1.5.0
- Node.js version: NA
- npm version: NA
- Platform/OS: Docker/linux
- Browser: NA

**Comment by knolleary** [comment]
Did this get addressed in 1.6?

**Comment by hardillb** [comment]
No, it got missed, I will do it now
