### ISSUE TITLE
Update to 1.6.1?

### ISSUE THREAD

**Issue by noahbliss-wh** [flowforge/docker-compose#83]
### Description

Just a heads-up, perhaps already known, that the docker setup doesn't configure the latest version.

**Comment by knolleary** [comment]
Thanks @noahbliss-wh - yes, this was overlooked as we prioritised getting k8s updated for our production environment. I'll update the docker-compose project now and update our release process to ensure we keep them in sync better.

**Comment by knolleary** [comment]
We've cut the 1.6.1 release of the docker-compose project.

The container is building as I type - you can follow it here: https://github.com/flowforge/docker-compose/actions/runs/4834202106

**Comment by knolleary** [comment]
The updated container is now available.
